export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './comments.service';
import { CommentsService } from './comments.service';
export * from './posts.service';
import { PostsService } from './posts.service';
export * from './productLists.service';
import { ProductListsService } from './productLists.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './replies.service';
import { RepliesService } from './replies.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [CategoriesService, CommentsService, PostsService, ProductListsService, ProductsService, RepliesService, UsersService];
