/**
 * Skin Hub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CommentDto } from '../model/commentDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CommentsService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param comment 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsCreatePost(comment?: CommentDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCommentsCreatePost(comment?: CommentDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCommentsCreatePost(comment?: CommentDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCommentsCreatePost(comment?: CommentDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/Comments/Create`,
            comment,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsDeleteCommentDelete(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCommentsDeleteCommentDelete(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCommentsDeleteCommentDelete(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCommentsDeleteCommentDelete(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/Comments/DeleteComment`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsGetAllCommentByPostIDGet(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CommentDto>>;
    public apiCommentsGetAllCommentByPostIDGet(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CommentDto>>>;
    public apiCommentsGetAllCommentByPostIDGet(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CommentDto>>>;
    public apiCommentsGetAllCommentByPostIDGet(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<CommentDto>>(`${this.basePath}/api/Comments/GetAllCommentByPostID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsGetAllCommentsByAuthorIDGet(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CommentDto>>;
    public apiCommentsGetAllCommentsByAuthorIDGet(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CommentDto>>>;
    public apiCommentsGetAllCommentsByAuthorIDGet(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CommentDto>>>;
    public apiCommentsGetAllCommentsByAuthorIDGet(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<CommentDto>>(`${this.basePath}/api/Comments/GetAllCommentsByAuthorID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param date 
     * @param name 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsGetAllCommentsByDateAndPostNameGet(date?: Date, name?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CommentDto>>;
    public apiCommentsGetAllCommentsByDateAndPostNameGet(date?: Date, name?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CommentDto>>>;
    public apiCommentsGetAllCommentsByDateAndPostNameGet(date?: Date, name?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CommentDto>>>;
    public apiCommentsGetAllCommentsByDateAndPostNameGet(date?: Date, name?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (date !== undefined) {
            queryParameters = queryParameters.set('date', <any>date.toISOString());
        }
        if (name !== undefined) {
            queryParameters = queryParameters.set('name', <any>name);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<CommentDto>>(`${this.basePath}/api/Comments/GetAllCommentsByDateAndPostName`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsGetAllCommentsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<CommentDto>>;
    public apiCommentsGetAllCommentsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CommentDto>>>;
    public apiCommentsGetAllCommentsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CommentDto>>>;
    public apiCommentsGetAllCommentsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<CommentDto>>(`${this.basePath}/api/Comments/GetAllComments`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsGetCommentByIDGet(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<CommentDto>;
    public apiCommentsGetCommentByIDGet(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CommentDto>>;
    public apiCommentsGetCommentByIDGet(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CommentDto>>;
    public apiCommentsGetCommentByIDGet(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<CommentDto>(`${this.basePath}/api/Comments/GetCommentByID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCommentsUpdateCommentPut(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<CommentDto>;
    public apiCommentsUpdateCommentPut(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CommentDto>>;
    public apiCommentsUpdateCommentPut(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CommentDto>>;
    public apiCommentsUpdateCommentPut(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.put<CommentDto>(`${this.basePath}/api/Comments/UpdateComment`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
