/**
 * Skin Hub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { PostDto } from '../model/postDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PostsService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsDeletePostDelete(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiPostsDeletePostDelete(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiPostsDeletePostDelete(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiPostsDeletePostDelete(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/Posts/DeletePost`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsGetAllPostsByCategoryIDGet(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<PostDto>>;
    public apiPostsGetAllPostsByCategoryIDGet(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PostDto>>>;
    public apiPostsGetAllPostsByCategoryIDGet(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PostDto>>>;
    public apiPostsGetAllPostsByCategoryIDGet(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PostDto>>(`${this.basePath}/api/Posts/GetAllPostsByCategoryID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param category 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsGetAllPostsByCategoryNameGet(category?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<PostDto>>;
    public apiPostsGetAllPostsByCategoryNameGet(category?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PostDto>>>;
    public apiPostsGetAllPostsByCategoryNameGet(category?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PostDto>>>;
    public apiPostsGetAllPostsByCategoryNameGet(category?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (category !== undefined) {
            queryParameters = queryParameters.set('category', <any>category);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PostDto>>(`${this.basePath}/api/Posts/GetAllPostsByCategoryName`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsGetAllPostsGet(observe?: 'body', reportProgress?: boolean): Observable<Array<PostDto>>;
    public apiPostsGetAllPostsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PostDto>>>;
    public apiPostsGetAllPostsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PostDto>>>;
    public apiPostsGetAllPostsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PostDto>>(`${this.basePath}/api/Posts/GetAllPosts`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param category 
     * @param date 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsGetPostByCategoryAndDateCreatedGet(category?: string, date?: Date, observe?: 'body', reportProgress?: boolean): Observable<Array<PostDto>>;
    public apiPostsGetPostByCategoryAndDateCreatedGet(category?: string, date?: Date, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PostDto>>>;
    public apiPostsGetPostByCategoryAndDateCreatedGet(category?: string, date?: Date, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PostDto>>>;
    public apiPostsGetPostByCategoryAndDateCreatedGet(category?: string, date?: Date, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (category !== undefined) {
            queryParameters = queryParameters.set('category', <any>category);
        }
        if (date !== undefined) {
            queryParameters = queryParameters.set('date', <any>date.toISOString());
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PostDto>>(`${this.basePath}/api/Posts/GetPostByCategoryAndDateCreated`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsGetPostByPostIDGet(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<PostDto>>;
    public apiPostsGetPostByPostIDGet(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PostDto>>>;
    public apiPostsGetPostByPostIDGet(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PostDto>>>;
    public apiPostsGetPostByPostIDGet(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PostDto>>(`${this.basePath}/api/Posts/GetPostByPostID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param date 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsGetPostsByDateGet(date?: Date, observe?: 'body', reportProgress?: boolean): Observable<Array<PostDto>>;
    public apiPostsGetPostsByDateGet(date?: Date, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PostDto>>>;
    public apiPostsGetPostsByDateGet(date?: Date, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PostDto>>>;
    public apiPostsGetPostsByDateGet(date?: Date, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (date !== undefined) {
            queryParameters = queryParameters.set('date', <any>date.toISOString());
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PostDto>>(`${this.basePath}/api/Posts/GetPostsByDate`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param postDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsPostCreatePost(postDto?: PostDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiPostsPostCreatePost(postDto?: PostDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiPostsPostCreatePost(postDto?: PostDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiPostsPostCreatePost(postDto?: PostDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/Posts/PostCreate`,
            postDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiPostsUpdatePut(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<PostDto>>;
    public apiPostsUpdatePut(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PostDto>>>;
    public apiPostsUpdatePut(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PostDto>>>;
    public apiPostsUpdatePut(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.put<Array<PostDto>>(`${this.basePath}/api/Posts/Update`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
