/**
 * Skin Hub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ReplyDto } from '../model/replyDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RepliesService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param reply 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepliesCreateReplyPost(reply?: ReplyDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiRepliesCreateReplyPost(reply?: ReplyDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiRepliesCreateReplyPost(reply?: ReplyDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiRepliesCreateReplyPost(reply?: ReplyDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/Replies/CreateReply`,
            reply,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepliesDeleteReplyDelete(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<ReplyDto>;
    public apiRepliesDeleteReplyDelete(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReplyDto>>;
    public apiRepliesDeleteReplyDelete(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReplyDto>>;
    public apiRepliesDeleteReplyDelete(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<ReplyDto>(`${this.basePath}/api/Replies/DeleteReply`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepliesGetAllRepliesByCommentIDGet(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<ReplyDto>>;
    public apiRepliesGetAllRepliesByCommentIDGet(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReplyDto>>>;
    public apiRepliesGetAllRepliesByCommentIDGet(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReplyDto>>>;
    public apiRepliesGetAllRepliesByCommentIDGet(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<ReplyDto>>(`${this.basePath}/api/Replies/GetAllRepliesByCommentID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepliesGetAllRepliesGet(observe?: 'body', reportProgress?: boolean): Observable<Array<ReplyDto>>;
    public apiRepliesGetAllRepliesGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ReplyDto>>>;
    public apiRepliesGetAllRepliesGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ReplyDto>>>;
    public apiRepliesGetAllRepliesGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<ReplyDto>>(`${this.basePath}/api/Replies/GetAllReplies`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepliesGetRepliesByIDGet(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<ReplyDto>;
    public apiRepliesGetRepliesByIDGet(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReplyDto>>;
    public apiRepliesGetRepliesByIDGet(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReplyDto>>;
    public apiRepliesGetRepliesByIDGet(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ReplyDto>(`${this.basePath}/api/Replies/GetRepliesByID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param ID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiRepliesUpdateReplyPut(ID?: number, observe?: 'body', reportProgress?: boolean): Observable<ReplyDto>;
    public apiRepliesUpdateReplyPut(ID?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReplyDto>>;
    public apiRepliesUpdateReplyPut(ID?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReplyDto>>;
    public apiRepliesUpdateReplyPut(ID?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ID !== undefined) {
            queryParameters = queryParameters.set('ID', <any>ID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.put<ReplyDto>(`${this.basePath}/api/Replies/UpdateReply`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
