/**
 * Skin Hub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ReplyDto {
    replyID?: number;
    replyBody?: string;
    replyAuthorID?: number;
    replyDate?: Date;
    commentID?: number;
}
