/**
 * Skin Hub API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserDto {
    userID?: number;
    firstName?: string;
    lastName?: string;
    emailAddress?: string;
    username?: string;
    gender?: UserDto.GenderEnum;
    skinColor?: UserDto.SkinColorEnum;
    isActive?: boolean;
    age?: number;
    registerDate?: Date;
    fullName?: string;
}
export namespace UserDto {
    export type GenderEnum = 1 | 2 | 3;
    export const GenderEnum = {
        NUMBER_1: 1 as GenderEnum,
        NUMBER_2: 2 as GenderEnum,
        NUMBER_3: 3 as GenderEnum
    }
    export type SkinColorEnum = 1 | 2 | 3 | 4;
    export const SkinColorEnum = {
        NUMBER_1: 1 as SkinColorEnum,
        NUMBER_2: 2 as SkinColorEnum,
        NUMBER_3: 3 as SkinColorEnum,
        NUMBER_4: 4 as SkinColorEnum
    }
}
